import Head from 'next/head'
import { useSession, signIn, signOut } from 'next-auth/react'
import { Box } from 'rebass'

import Landing from '../components/pages/Landing'

export default function Home () {
  const { data: session } = useSession()

  if (!session) {
    return <Landing/>
  }

  console.log(session)
  const { user } = session
  return (
    <div>
      <Head>
        <title>Welcome</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <Box>
        <div>Welcome {user.name}</div>
        <div onClick={() => signOut()}>Logout</div>
      </Box>
    </div>
  )
}
